INSERT INTO USER (NAME, DATE_OF_BIRTH) VALUES ('Karlos', TO_DATE('1985/02/24', 'yyyy/mm/dd'));
INSERT INTO USER (NAME, DATE_OF_BIRTH) VALUES ('Claudia', TO_DATE('1988/08/24', 'yyyy/mm/dd'));
INSERT INTO USER (NAME, DATE_OF_BIRTH) VALUES ('Susana', TO_DATE('1998/11/02', 'yyyy/mm/dd'));
